active_border_color #000000
background_opacity 0.95
cursor_shape block
cursor_trail 3
cursor_trail_decay 0.1 0.4
enabled_layouts splits
font_family Iosevka Term Semibold
inactive_text_alpha 0.6
map ctrl+s launch --location=hsplit --cwd=current
map ctrl+shift+0 change_font_size all 0
map ctrl+shift+backspace combine : clear_terminal scroll active : clear_terminal scrollback active
map ctrl+shift+f launch --type=overlay --stdin-source=@screen_scrollback nvim -R +"set buftype=nofile" +"noremap q ZQ" -
map ctrl+shift+h previous_window
map ctrl+shift+l next_window
map ctrl+shift+s launch --location=vsplit --cwd=current
tab_bar_style powerline
tab_powerline_style slanted
window_padding_width 4

# https://github.com/folke/tokyonight.nvim/blob/main/extras/kitty/tokyonight_night.conf
background #1a1b26
foreground #c0caf5
selection_background #283457
selection_foreground #c0caf5
url_color #73daca
cursor #c0caf5
cursor_text_color #1a1b26

# Tabs
active_tab_background #7aa2f7
active_tab_foreground #16161e
inactive_tab_background #292e42
inactive_tab_foreground #545c7e
#tab_bar_background #15161e

# Windows
active_border_color #7aa2f7
inactive_border_color #292e42

# normal
color0 #15161e
color1 #f7768e
color2 #9ece6a
color3 #e0af68
color4 #7aa2f7
color5 #bb9af7
color6 #7dcfff
color7 #a9b1d6

# bright
color8  #414868
color9  #ff899d
color10 #9fe044
color11 #faba4a
color12 #8db0ff
color13 #c7a9ff
color14 #a4daff
color15 #c0caf5

# extended colors
color16 #ff9e64
color17 #db4b4b
