---
- name: Setup Fedora
  hosts: localhost
  gather_facts: false
  vars:
    packages:
      - "@development-tools"
      - ImageMagick
      - ShellCheck
      - ansible
      - awscli2
      - bat
      - black
      - btop
      - difftastic
      - dnf5
      - dnf5-plugins
      - evolution
      - eza
      - fastfetch
      - fd-find
      - fontconfig-devel
      - freetype-devel
      - fzf
      - gcc-c++
      - gnome-shell-extension-gpaste
      - gnome-tweaks
      - gpaste
      - gum
      - hadolint
      - heif-pixbuf-loader
      - iosevka-term-fonts
      - java-latest-openjdk-devel
      - libstdc++-devel
      - libxcb-devel
      - neovim
      - nodejs
      - nodejs-bash-language-server
      - npm
      - opam
      - papirus-icon-theme
      - podman-compose
      - rlwrap
      - terraform
      - terraform-ls
      - tokei
      - v4l-utils
      - youtube-dl
      - zoxide
      - zsh
    flatpaks:
      - com.github.johnfactotum.Foliate
      - com.github.tchx84.Flatseal
      - io.github.amit9838.mousam
      - io.github.ungoogled_software.ungoogled_chromium
      - org.ferdium.Ferdium
      - org.localsend.localsend_app
      - org.pipewire.Helvum
      - org.signal.Signal
      - org.videolan.VLC
      - org.wezfurlong.wezterm
      - us.zoom.Zoom
  tasks:
    - name: Get Fedora version
      shell: rpm -E %fedora
      register: fedora_version
    - name: Install RPM fusion
      become: true
      ansible.builtin.dnf5:
        name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version.stdout }}.noarch.rpm"
        state: present
        install_weak_deps: no
    - name: Install Hashicorp repo
      become: true
      command: dnf config-manager --add-repo=https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    - name: Add charm repo
      become: true
      ansible.builtin.yum_repository:
        name: Charm
        description: RPM repo for Charm
        file: charm
        baseurl: https://repo.charm.sh/yum/
        gpgcheck: 1
        gpgkey: https://repo.charm.sh/yum/gpg.key
    - name: Enable iosevka copr
      become: true
      community.general.copr:
        state: enabled
        name: peterwu/iosevka
    - name: Installing packages
      become: true
      ansible.builtin.dnf5:
        name: "{{ packages }}"
        state: latest
        install_weak_deps: no
      register: result
      until: result is successful
    - name: Installing flatpaks
      become: true
      flatpak:
        name: "{{ flatpaks }}"
        state: present
      register: result
      until: result is successful
    - name: Installing npm packages
      become: true
      npm:
        name: "{{ item }}"
        state: present
        global: yes
      register: result
      until: result is successful
      with_items:
        - prettier
        - yaml-language-server
    - name: Common tasks
      include_tasks: "common.yml"
      vars:
        conf_dir: "{{ lookup('env','HOME') }}/.config"
        src_dir: "{{ playbook_dir | dirname }}"
        symlinks:
          - git
          - nvim
          - ripgrep
          - wezterm
