---
- name: Install Fedora packages
  hosts: localhost
  become: true
  vars:
    packages:
      - ansible
      - bat
      - black
      - bottom
      - "@development-tools"
      - fd-find
      - fontconfig-devel
      - freetype-devel
      - fzf
      - gcc-c++
      - gnome-shell-extension-gpaste
      - gnome-tweaks
      - gpaste
      - hadolint
      - ImageMagick
      - java-latest-openjdk-devel
      - libstdc++-devel
      - libxcb-devel
      - lsd
      - neofetch
      - neovim
      - nodejs
      - npm
      - papirus-icon-theme
      - podman-compose
      - rlwrap
      - ShellCheck
      - terraform
      - terraform-ls
      - vlc
      - youtube-dl
      - zsh
    flatpaks:
      - com.github.johnfactotum.Foliate
      - com.spotify.Client
      - org.ferdium.Ferdium
      - org.mozilla.Thunderbird
      - org.signal.Signal
      - org.telegram.desktop
      - org.wezfurlong.wezterm
      - us.zoom.Zoom
  tasks:
    - name: Get Fedora version
      shell: rpm -E %fedora
      register: fedora_version
    - name: Prep dnf
      command: "{{ item }}"
      with_items:
        - dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version.stdout }}.noarch.rpm
        - dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    - name: Installing packages
      dnf:
        name: "{{ packages }}"
        state: present
        install_weak_deps: no
      register: result
      until: result is successful
    - name: Installing flatpaks
      flatpak:
        name: "{{ flatpaks }}"
        state: present
      register: result
      until: result is successful
    - name: Installing npm packages
      npm:
        name: "{{ item }}"
        state: present
        global: yes
      register: result
      until: result is successful
      with_items:
        - prettier
        - pyright
        - yaml-language-server
