---
- name: Install Fedora packages
  hosts: localhost
  become: true
  vars:
    packages:
      - "@development-tools"
      - ImageMagick
      - ShellCheck
      - ansible
      - awscli2
      - bat
      - black
      - bottom
      - btop
      - difftastic
      - dnf5
      - dnf5-plugins
      - fd-find
      - fontconfig-devel
      - freetype-devel
      - fzf
      - gcc-c++
      - gnome-shell-extension-gpaste
      - gnome-tweaks
      - gpaste
      - gum
      - hadolint
      - java-latest-openjdk-devel
      - libstdc++-devel
      - libxcb-devel
      - lsd
      - neofetch
      - neovim
      - nodejs
      - nodejs-bash-language-server
      - npm
      - opam
      - papirus-icon-theme
      - podman-compose
      - rlwrap
      - terraform
      - terraform-ls
      - v4l-utils
      - xsel
      - youtube-dl
      - zsh
    flatpaks:
      - com.github.johnfactotum.Foliate
      - org.ferdium.Ferdium
      - org.localsend.localsend_app
      - org.mozilla.Thunderbird
      - org.signal.Signal
      - org.videolan.VLC
      - org.wezfurlong.wezterm
      - us.zoom.Zoom
  tasks:
    - name: Get Fedora version
      shell: rpm -E %fedora
      register: fedora_version
    - name: Prep dnf
      command: "{{ item }}"
      with_items:
        - dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version.stdout }}.noarch.rpm
        - dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    - name: Add charm repo
      ansible.builtin.yum_repository:
        name: Charm
        description: RPM repo for Charm
        file: charm
        baseurl: https://repo.charm.sh/yum/
        gpgcheck: 1
        gpgkey: https://repo.charm.sh/yum/gpg.key
    - name: Installing packages
      dnf:
        name: "{{ packages }}"
        state: present
        install_weak_deps: no
      register: result
      until: result is successful
    - name: Installing flatpaks
      flatpak:
        name: "{{ flatpaks }}"
        state: present
      register: result
      until: result is successful
    - name: Installing npm packages
      npm:
        name: "{{ item }}"
        state: present
        global: yes
      register: result
      until: result is successful
      with_items:
        - prettier
        - pyright
        - yaml-language-server
