---
- name: Install Mac packages
  hosts: localhost
  become: false
  vars:
    brews:
      - ansible
      - autoconf
      - asdf
      - astyle
      - aws-vault
      - python
      - awscli
      - bash
      - bat
      - black
      - bottom
      - boxes
      - cfr-decompiler
      - clojure
      - cmatrix
      - colima
      - cowsay
      - curl
      - deno
      - difftastic
      - docker
      - docker-machine-driver-hyperkit
      - dog
      - elixir
      - elm
      - exiftool
      - faac
      - fd
      - fennel
      - ffmpeg
      - flex
      - fortune
      - fzf
      - gcc
      - ghc
      - git
      - git-crypt
      - git-delta
      - git-extras
      - git-quick-stats
      - glances
      - glow
      - gnu-sed
      - go
      - gopls
      - gpgme
      - gradle
      - grep
      - hadolint
      - hashcat
      - haskell-stack
      - helm
      - httpie
      - hub
      - ipython
      - ispell
      - jq
      - jsonnet
      - kind
      - libgit2
      - libscrypt
      - libuv
      - llvm
      - lolcat
      - lsd
      - magic-wormhole
      - make
      - markdown
      - maven
      - minikube
      - mypy
      - neofetch
      - neovim
      - ninja
      - nmap
      - nss
      - onefetch
      - openssl@3
      - p7zip
      - packer
      - parallel
      - pgcli
      - planck
      - podman
      - prettier
      - prettyping
      - progress
      - pulumi
      - pwgen
      - pyright
      - ripgrep
      - ruby
      - sbt
      - scc
      - shellcheck
      - sl
      - socat
      - speedtest-cli
      - stylua
      - telnet
      - terminal-notifier
      - tfsec
      - thefuck
      - tig
      - tree
      - unar
      - watch
      - websocat
      - wget
      - wrk
      - xh
      - yarn
      - youtube-dl
      - yq
      - zoxide
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - borkdude/brew/babashka
      - clojure-lsp/brew/clojure-lsp-native
      - deviceinsight/packages/kafkactl
      - gromgit/fuse/ntfs-3g-mac
      - hashicorp/tap/terraform-ls
      - koekeishiya/formulae/skhd
      - koekeishiya/formulae/yabai
    casks:
      - eloston-chromium
      - ferdi
      - flux
      - font-fantasque-sans-mono-nerd-font
      - font-fira-code-nerd-font
      - font-jetbrains-mono-nerd-font
      - graalvm-ce-java17
      - maccy
      - macfuse
      - macpass
      - qlvideo
      - temurin
      - vimr
      - visualvm
      - vlc
      - wezterm
      - zprint
    npms:
      - yaml-language-server
  tasks:
    - name: Installing brews
      homebrew:
        name: "{{ brews }}"
        state: present
      register: result
      until: result is successful
    - name: Installing casks
      homebrew_cask:
        name: "{{ casks }}"
        state: present
      register: result
      until: result is successful
    - name: Installing npm packages
      npm:
        name: "{{ npms | join(' ') }}"
        state: present
        global: yes
      register: result
      until: result is successful
